# https://kubernetes.io/ja/docs/concepts/workloads/controllers/deployment/
# 自動でPodの数の増減や維持ができるReplicaSetは直接使わず、deploymentを使うことが推奨されている
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          # docker build -f ./containers/fastapi/Dockerfile.dev -t kubernetes-fastapi-app:latest .
          image: kubernetes-fastapi-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              value: 'test'
            - name: ALGORITHM
              value: 'HS256'
            - name: SQLALCHEMY_DATABASE_URL
              value: 'postgresql://postgres:postgres@db:5432/postgres'
            - name: SENDGRID_API_KEY
              value: 'test'
            - name: COOKIE_SAME_SITE
              value: 'Lax'
