# https://kubernetes.io/ja/docs/concepts/workloads/pods/disruptions/#pod-disruption-budget
# https://engineering.mercari.com/blog/entry/20231204-k8s-understanding-pdb/
# システムの計画的な中断からapplicationを保護するKubernetesの起動
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: default
  name: {{.Release.Name}}
  labels: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Release.Name}}
