name: build and push docker image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
      # https://github.com/docker/login-action
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: application
          file: ./containers/fastapi/Dockerfile.dev
          push: true
          tags: kubernetes-fastapi-app:latest
